name: codux
description: Codux is a state management library inspired by Redux.
version: 0.0.3
homepage: https://github.com/oh-jinsu/codux

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: